### ISSUE TITLE
Use Celery for background tasks

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/jarbas#217]
Jarbas is starting to have a kind of overhead in terms of background tasks — currently ran manually or via `cronjob`:

- [x] ~~`python manage.py reimbursements`: to load `reimbursements.xz` generated by Rosie~~ #240 
- [ ] `python manage.py irregularities`:  to load `suspicions.xz` generated by Rosie
- [ ] `python manage.py receipts`: to check if the expected receipt URL existis
- [ ] `python manage.py tweets`: to check for @RosieDaSerenata tweets

These tasks would be better handled by Celery IMHO

**Comment by cuducos** [comment]
After talking to @davinirjr I'm back to update this issue:

* `python manage.py tweets` is very quick script and can be managed (by now) via `cron` IMHO
* `python manage.py receipts` is slow not because of our infra structure, but because it has to pause from time to time to avoid being blocked by the Chamber of Deputies servers — IMHO there's no problem in keeping that in `cron` too

The problem real bottleneck is the pipeline `python manage.py reimbursements` and `python manage.py suspicions` (former `irregularities`) — today this is how it works

1. Manually run Rosie
2. Use `scp` to upload the CSV to Jarbas server
3. Use `ssh` to run the first command (`reimbursements`)
4. Wait until eternity
5. Use `ssh` to run the second command (`suspicions `)
6. Wait until eternity again

We have to wait until eternity because each line of each CSV generates two return trips to the database: first check if the record exists, then there is a `create` if it's new data or `update` if it's existing data. We can't do `bulk_*` because we use `django-simple-history` to keep track of changes in reimbursement data (something the Chamber does not, or at least publicly does not). What I mean is that, for example, if a congressperson gives back the money from a given reimbursement the Chamber's API simply exclude any data related to this reimbursement from its API.

However using Celery can turn this double eternity waiting way faster. We read the CSV and delay the real execution. This way the solution @davinirjr suggested is as follow:

* At the end of Rosie  process she can send a HTTP request to an authenticated Jarbas API for each CSV line (maybe combining `reimbursements` and `suspicions` data)
* With Celery Jarbas can quickly respond to these requests delaying the execution of this tasks

That way we completely get rid of the manual `scp`, `ssh` steps and of any waiting at all in Jarbas. Rosie will get a bit slower at the end if user opts to send data to Jarbas, but as her processes takes more 1 hour the impact might not that huge in terms of UX.

Ideas @jtemporal @lipemorais @irio @anaschwendler?

**Comment by davinirjr** [comment]
Keep in mind that as Rosie send data to Jarbas, it will be just data transfer (over the wire), and we can (and should) GZIP it. Rosie doesn't need to (and shoudn't) wait Jarbas commit on database.

We achieve this by implementing worker queue (with Jarbas in front of it for - at least, a thin layer of - security).

I'll love to get some video or audio with you, to explain it in details. @cuducos and @jtemporal already have my contact on Telegram. Ping me if you'd like too.

**Comment by decko** [comment]
@davinirjr Are you working this? If so, I could help on something needed...

**Comment by davinirjr** [comment]
Nope, @decko.

You can go for it, just align with @cuducos.

**Comment by cuducos** [comment]
Closed - importations doesn't take so long anymore after #316
